export enum MenuViews {
  NOTIFICATION_LIST,
  PROFILE_MENU_LIST,
  WISH_MENU_LIST,
  MEGA_MENU_LIST,
  TIMELINE_LIST
}

export enum SubMenuViews {
  ADMINISTRATION_MENU,
  WORKFLOW_MENU,
  SYSTEM_SETUP_MENU,
  CLIENT_MENU,
  BILLING_MENU,
  REPORT_MENU,
  EMAIL_MENU,
  HRMS_MENU
}
